#!/usr/bin/env python3
# Copyright 2026 The Lynxtron Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import argparse
import base64
import os
import re


BASE64_WASM_RE = re.compile(
    r'Buffer\d*\.from\("([A-Za-z0-9+/=]+)", "base64"\)'
)


def write_if_changed(path, data, mode="w"):
  old_data = None
  if os.path.exists(path):
    with open(path, "rb" if "b" in mode else "r") as file:
      old_data = file.read()
  if old_data == data:
    return
  os.makedirs(os.path.dirname(path), exist_ok=True)
  with open(path, mode) as file:
    file.write(data)


def generate_header():
  return """// Generated by src/script/node/generate_amaro_raw_wasm.py.

#ifndef SRC_AMARO_WASM_DATA_H_
#define SRC_AMARO_WASM_DATA_H_

#include <cstddef>
#include <cstdint>

namespace node {
namespace builtins {

extern const uint8_t amaro_wasm_data[];
extern const size_t amaro_wasm_size;

}  // namespace builtins
}  // namespace node

#endif  // SRC_AMARO_WASM_DATA_H_
"""


def generate_cc(data):
  lines = [
      "// Generated by src/script/node/generate_amaro_raw_wasm.py.",
      "",
      '#include "amaro_wasm_data.h"',
      "",
      "namespace node {",
      "namespace builtins {",
      "",
      "extern const uint8_t amaro_wasm_data[] = {",
  ]

  for offset in range(0, len(data), 12):
    chunk = data[offset:offset + 12]
    values = ", ".join(f"0x{byte:02x}" for byte in chunk)
    lines.append(f"    {values},")

  lines.extend([
      "};",
      "",
      "extern const size_t amaro_wasm_size = sizeof(amaro_wasm_data);",
      "",
      "}  // namespace builtins",
      "}  // namespace node",
      "",
  ])
  return "\n".join(lines)


def main():
  parser = argparse.ArgumentParser(
      description="Split Amaro's inline base64 wasm into raw C++ bytes.")
  parser.add_argument("--input", required=True)
  parser.add_argument("--output-js", required=True)
  parser.add_argument("--output-cc", required=True)
  parser.add_argument("--output-h", required=True)
  args = parser.parse_args()

  with open(args.input, encoding="utf-8") as file:
    source = file.read()

  matches = list(BASE64_WASM_RE.finditer(source))
  if len(matches) != 1:
    raise RuntimeError(f"expected exactly one Amaro wasm base64 blob, got {len(matches)}")

  wasm = base64.b64decode(matches[0].group(1), validate=True)
  if not wasm.startswith(b"\0asm"):
    raise RuntimeError("decoded Amaro payload is not a wasm binary")

  patched_source = (
      source[:matches[0].start()] +
      'internalBinding("builtins").getAmaroWasmBytes()' +
      source[matches[0].end():]
  )

  write_if_changed(args.output_js, patched_source)
  write_if_changed(args.output_h, generate_header())
  write_if_changed(args.output_cc, generate_cc(wasm))


if __name__ == "__main__":
  main()
