name: ci

on:
  pull_request:
  push:
    branches:
      - CQ-*

defaults:
  run:
    working-directory: src

jobs:
  static-check:
    runs-on: lynx-ubuntu-22.04-medium
    timeout-minutes: 30
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
          path: src/lynxtron
      - name: Run file type check
        run: |
          ls -al
