// Copyright 2026 The Lynxtron Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

export const commerceStandardMock = {
  user: {
    id: 'user-lynx-001',
    name: 'Mina Chen',
    tier: 'Gold member',
    city: 'Shanghai',
    points: 4820,
    coupons: 6,
  },
  tabs: [
    { id: 'recommend', label: 'Recommend' },
    { id: 'profile', label: 'Profile' },
  ],
  home: {
    title: 'Lynx Market',
    subtitle: 'Daily Picks',
    cartLabel: 'Cart 2',
    chips: ['All', 'Home', 'Wear', 'Tech'],
  },
  products: [
    {
      id: 'p-nova-lamp',
      name: 'Nova Desk Lamp',
      price: '$48',
      rating: '4.8',
      sold: '1.2k sold',
      badge: 'Top Pick',
      detailTitle: 'Detail Nova Desk Lamp',
      detailSubtitle: 'Warm dimmable light for compact workspaces.',
      inventory: 'Inventory 24',
      shipping: 'Delivery tomorrow',
      option: 'Color Sage',
    },
    {
      id: 'p-orbit-jacket',
      name: 'Orbit Knit Jacket',
      price: '$72',
      rating: '4.7',
      sold: '860 sold',
      badge: 'New',
      detailTitle: 'Detail Orbit Knit Jacket',
      detailSubtitle: 'Soft layered knit with a weather resistant shell.',
      inventory: 'Inventory 18',
      shipping: 'Delivery Friday',
      option: 'Size M',
    },
    {
      id: 'p-canvas-tote',
      name: 'Canvas Mini Tote',
      price: '$36',
      rating: '4.9',
      sold: '2.1k sold',
      badge: 'Hot',
      detailTitle: 'Detail Canvas Mini Tote',
      detailSubtitle: 'Structured cotton tote with an inner zipper pocket.',
      inventory: 'Inventory 42',
      shipping: 'Delivery tomorrow',
      option: 'Color Oat',
    },
    {
      id: 'p-pulse-speaker',
      name: 'Pulse Travel Speaker',
      price: '$59',
      rating: '4.6',
      sold: '740 sold',
      badge: 'Deal',
      detailTitle: 'Detail Pulse Travel Speaker',
      detailSubtitle: 'Pocket speaker with splash protection and deep bass.',
      inventory: 'Inventory 31',
      shipping: 'Delivery Saturday',
      option: 'Color Ink',
    },
    {
      id: 'p-bloom-mug',
      name: 'Bloom Ceramic Mug',
      price: '$22',
      rating: '4.8',
      sold: '980 sold',
      badge: 'Gift',
      detailTitle: 'Detail Bloom Ceramic Mug',
      detailSubtitle: 'Hand glazed mug with a heat holding rounded body.',
      inventory: 'Inventory 55',
      shipping: 'Delivery tomorrow',
      option: 'Color Coral',
    },
    {
      id: 'p-zen-mat',
      name: 'Zen Desk Mat',
      price: '$31',
      rating: '4.7',
      sold: '670 sold',
      badge: 'Focus',
      detailTitle: 'Detail Zen Desk Mat',
      detailSubtitle: 'Low profile mat for keyboard, mouse, and notes.',
      inventory: 'Inventory 29',
      shipping: 'Delivery Thursday',
      option: 'Color Charcoal',
    },
    {
      id: 'p-terra-kit',
      name: 'Terra Pour Over Kit',
      price: '$64',
      rating: '4.9',
      sold: '410 sold',
      badge: 'Craft',
      detailTitle: 'Detail Terra Pour Over Kit',
      detailSubtitle: 'Ceramic dripper set with glass server and filters.',
      inventory: 'Inventory 16',
      shipping: 'Delivery Sunday',
      option: 'Set 02',
    },
    {
      id: 'p-metro-pack',
      name: 'Metro Sling Pack',
      price: '$54',
      rating: '4.5',
      sold: '530 sold',
      badge: 'Travel',
      detailTitle: 'Detail Metro Sling Pack',
      detailSubtitle: 'Compact crossbody pack with tablet-safe storage.',
      inventory: 'Inventory 21',
      shipping: 'Delivery Friday',
      option: 'Color Navy',
    },
    {
      id: 'p-aero-stand',
      name: 'Aero Laptop Stand',
      price: '$46',
      rating: '4.6',
      sold: '790 sold',
      badge: 'Desk',
      detailTitle: 'Detail Aero Laptop Stand',
      detailSubtitle: 'Foldable aluminum stand with six height positions.',
      inventory: 'Inventory 38',
      shipping: 'Delivery tomorrow',
      option: 'Finish Silver',
    },
    {
      id: 'p-luma-cable',
      name: 'Luma Braided Cable',
      price: '$18',
      rating: '4.7',
      sold: '3.4k sold',
      badge: 'Saver',
      detailTitle: 'Detail Luma Braided Cable',
      detailSubtitle: 'Fast charge braided cable with reinforced ends.',
      inventory: 'Inventory 120',
      shipping: 'Delivery tomorrow',
      option: 'Length 1m',
    },
  ],
  history: [
    { id: 'h-001', label: 'Viewed Nova Desk Lamp', time: 'Today 09:18' },
    { id: 'h-002', label: 'Viewed Canvas Mini Tote', time: 'Yesterday 21:04' },
    { id: 'h-003', label: 'Bought Luma Braided Cable', time: 'May 27 14:32' },
  ],
  settings: [
    { id: 's-address', label: 'Address Book', value: '2 saved' },
    { id: 's-payment', label: 'Payment Methods', value: 'Visa 2048' },
    { id: 's-notify', label: 'Notification Settings', value: 'Deals on' },
  ],
} as const;
