name: install common dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: "2"
    required: false
  cache-backend:
    description: cache backend for habitat
    default: "lynx-infra"
    required: false
  target:
    description: habitat target
    default: ""
    required: false
  target_only:
    description: only install dependencies for the target
    default: "false"
    required: false
  run-habitat-sync:
    description: whether to run habitat sync
    default: "true"
    required: false
  # actions/cache stores files with relative directory, which causes inconsistency between self-hosted runner and
  # container runner. Therefore, add this temporary option to modify cache key prefix as a workaround. Delete this when
  # we are able to adjust the container runner's directory structure to the same as self-hosted runner.
  cache-key-prefix:
    description: cache key prefix for cache action
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: setup cache action
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ~/.habitat_cache
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('lynxtron/.habitat', 'lynxtron/src/dependencies/DEPS') }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: setup cache action
      if: ${{ inputs.cache-backend == 'github' }}
      uses: actions/cache@v4
      with:
        path: ~/.habitat_cache
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('lynxtron/.habitat', 'lynxtron/src/dependencies/DEPS') }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: run habitat sync
      if: ${{ inputs.run-habitat-sync == 'true' }}
      shell: bash
      working-directory: lynxtron/src
      run: |
        set -x
        if [[ "${{ inputs.target }}" == "" ]]; then
          ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync .
        elif [[ "${{ inputs.target_only }}" == "true" ]]; then
          ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync . --target ${{ inputs.target }} --target-only
        else
          ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync . --target ${{ inputs.target }}
        fi
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
        GIT_LFS_SKIP_SMUDGE: 1
