name: ci

on:
  pull_request:
  push:
    branches:
      - CQ-*

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: lynxtron

jobs:
  static-check:
    runs-on: lynx-ubuntu-22.04-medium
    timeout-minutes: 30
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
          path: lynxtron
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Install Common Dependencies
        uses: ./lynxtron/.github/actions/common-deps
        with:
          target: 'tools_shared'
          target_only: 'true'
      - name: Run file type check
        run: |
          cd ${{ github.workspace }}/lynxtron
          source lynxtron_tools/envsetup.sh
          python3 -m pip install requests
          python3 src/tools_shared/git_lynx.py check --checkers file-type
      - name: Run cpplint check
        run: |
          cd ${{ github.workspace }}/lynxtron
          source lynxtron_tools/envsetup.sh
          python3 src/tools_shared/git_lynx.py check --checkers cpplint
      - name: Run commit-message check
        run: |
          cd ${{ github.workspace }}/lynxtron
          source lynxtron_tools/envsetup.sh
          python3 src/tools_shared/git_lynx.py check --checkers commit-message
      - name: Run coding-style check
        run: |
          cd ${{ github.workspace }}/lynxtron
          source lynxtron_tools/envsetup.sh
          which gn
          gn --version
          python3 src/tools_shared/git_lynx.py check --checkers coding-style
  macos-lynxtron-build:
    timeout-minutes: 120
    runs-on: lynx-darwin-14-medium
    strategy:
      matrix:
        arch: [arm64]
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynxtron
      - name: Build macOS Lynxtron
        uses: ./lynxtron/.github/actions/macos-lynxtron-build
        with:
          build-arch: ${{ matrix.arch }}
  windows-lynxtron-build:
    timeout-minutes: 120
    runs-on: lynx-windows-2022-large
    strategy:
      matrix:
        arch: [x64]
    steps:
      - name: Configure Git
        shell: PowerShell
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global http.sslBackend "schannel"
        working-directory: ./
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynxtron
      - name: Build Windows Lynxtron
        uses: ./lynxtron/.github/actions/windows-lynxtron-build
        with:
          build-arch: ${{ matrix.arch }}
